services:
  node-1:
  
    image: gozargah/marzban-node:latest
    restart: always
    network_mode: host

    volumes:
      - /var/lib/marzban-node:/var/lib/marzban-node
      - /var/lib/marzban:/var/lib/marzban

    environment:
      SERVICE_PORT: 5001
      XRAY_API_PORT: 6001
 #     SSL_CERT_FILE: "/var/lib/marzban-node/ssl_cert.pem"
 #     SSL_KEY_FILE: "/var/lib/marzban-node/ssl_key.pem"
      SSL_CLIENT_CERT_FILE: "/var/lib/marzban-node/server1.pem"
      SERVICE_PROTOCOL: rest
  
  node-2:
  
    image: gozargah/marzban-node:latest
    restart: always
    network_mode: host

    volumes:
      - /var/lib/marzban-node:/var/lib/marzban-node
      - /var/lib/marzban:/var/lib/marzban

    environment:
      SERVICE_PORT: 5002
      XRAY_API_PORT: 6002
  #    SSL_CERT_FILE: "/var/lib/marzban-node/ssl_cert.pem"
  #    SSL_KEY_FILE: "/var/lib/marzban-node/ssl_key.pem"
      SSL_CLIENT_CERT_FILE: "/var/lib/marzban-node/server2.pem"
      SERVICE_PROTOCOL: rest
